"""
Security event scenarios for the SOC Analyst environment.

Each scenario defines a security event with full user metadata, event
details, the correct action, the threat tier, and a human-readable
explanation. Scenarios are grouped by task difficulty.

Threat Tiers:
  - TIER_1_CRITICAL: Ransomware, credential harvesting → BAN
  - TIER_2_HIGH: Impossible travel, brute force → SUSPEND
  - TIER_3_MEDIUM: New device + bulk download, after-hours login → VERIFY
  - BENIGN: Normal user activity → PERMIT
"""

from dataclasses import dataclass, field
from typing import List


@dataclass
class SecurityEvent:
    """A single security event scenario with ground truth."""

    # User metadata
    user_id: str
    job_role: str
    department: str
    typical_login_hours: str
    registered_devices: list

    # Event data
    timestamp: str
    source_ip: str
    geo_location: str
    action_string: str
    payload_size_mb: float
    device_id: str
    failed_login_count: int
    previous_login_location: str
    previous_login_timestamp: str

    # Ground truth
    correct_action: str     # PERMIT, VERIFY, SUSPEND, BAN
    threat_tier: str        # TIER_1_CRITICAL, TIER_2_HIGH, TIER_3_MEDIUM, BENIGN
    explanation: str        # Why this is the correct action


# =============================================================================
# EASY TASK — 10 events, obvious signatures, no tricks
# =============================================================================

EASY_EVENTS: List[SecurityEvent] = [
    # --- TIER 1: CRITICAL (BAN) ---
    SecurityEvent(
        user_id="USR-1042",
        job_role="Contractor",
        department="External",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-8821"],
        timestamp="2025-03-15T14:22:31Z",
        source_ip="198.51.100.45",
        geo_location="Unknown VPN Exit Node",
        action_string="vssadmin delete shadows /all /quiet",
        payload_size_mb=0.01,
        device_id="DEV-WIN-8821",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-03-15T09:01:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Ransomware signature: 'vssadmin delete shadows' deletes Volume Shadow Copies, a primary indicator of ransomware deployment.",
    ),
    SecurityEvent(
        user_id="USR-2091",
        job_role="Intern",
        department="Marketing",
        typical_login_hours="10:00-18:00",
        registered_devices=["DEV-WIN-3310"],
        timestamp="2025-03-15T15:45:12Z",
        source_ip="203.0.113.77",
        geo_location="Shanghai, China",
        action_string="mimikatz.exe sekurlsa::logonpasswords",
        payload_size_mb=0.5,
        device_id="DEV-WIN-3310",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-03-15T10:00:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Credential harvesting: mimikatz is used to extract plaintext credentials from LSASS memory.",
    ),
    SecurityEvent(
        user_id="USR-3015",
        job_role="Contractor",
        department="External",
        typical_login_hours="08:00-16:00",
        registered_devices=["DEV-WIN-5501"],
        timestamp="2025-03-16T02:14:55Z",
        source_ip="192.0.2.199",
        geo_location="Moscow, Russia",
        action_string="procdump.exe -ma lsass.exe lsass.dmp",
        payload_size_mb=0.3,
        device_id="DEV-WIN-5501",
        failed_login_count=0,
        previous_login_location="London, UK",
        previous_login_timestamp="2025-03-15T15:30:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="LSASS dump via procdump: Credential harvesting technique equivalent to mimikatz.",
    ),

    # --- TIER 2: HIGH (SUSPEND) ---
    SecurityEvent(
        user_id="USR-5501",
        job_role="Sales Manager",
        department="Sales",
        typical_login_hours="08:00-18:00",
        registered_devices=["DEV-MAC-2201", "DEV-MOB-2202"],
        timestamp="2025-03-15T11:30:00Z",
        source_ip="45.33.32.156",
        geo_location="Tokyo, Japan",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-MAC-2201",
        failed_login_count=0,
        previous_login_location="London, UK",
        previous_login_timestamp="2025-03-15T11:05:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Impossible travel: Login from London and then Tokyo within 25 minutes is physically impossible.",
    ),
    SecurityEvent(
        user_id="USR-6010",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-4401"],
        timestamp="2025-03-15T09:42:00Z",
        source_ip="10.0.0.55",
        geo_location="Chicago, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-4401",
        failed_login_count=127,
        previous_login_location="Chicago, US",
        previous_login_timestamp="2025-03-14T17:00:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Brute force: 127 consecutive failed logins followed by a success indicates a brute force attack.",
    ),

    # --- TIER 3: MEDIUM (VERIFY) ---
    SecurityEvent(
        user_id="USR-7022",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-6601"],
        timestamp="2025-03-15T13:15:00Z",
        source_ip="10.0.1.30",
        geo_location="San Francisco, US",
        action_string="file_download bulk_export",
        payload_size_mb=2500.0,
        device_id="DEV-NEW-9999",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-03-15T09:00:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="Insider threat indicator: New unregistered device combined with 2.5GB bulk download.",
    ),
    SecurityEvent(
        user_id="USR-8033",
        job_role="Designer",
        department="Marketing",
        typical_login_hours="10:00-19:00",
        registered_devices=["DEV-MAC-7701"],
        timestamp="2025-03-16T03:22:00Z",
        source_ip="10.0.2.15",
        geo_location="San Francisco, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-MAC-7701",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-03-15T18:00:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="After-hours login: Login at 3:22 AM is well outside the user's typical 10:00-19:00 window.",
    ),

    # --- BENIGN (PERMIT) ---
    SecurityEvent(
        user_id="USR-4001",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-1101"],
        timestamp="2025-03-15T10:15:00Z",
        source_ip="10.0.0.22",
        geo_location="San Francisco, US",
        action_string="git push origin main",
        payload_size_mb=5.2,
        device_id="DEV-MAC-1101",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-03-15T09:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: Routine git push during business hours from registered device.",
    ),
    SecurityEvent(
        user_id="USR-4002",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="08:00-17:00",
        registered_devices=["DEV-WIN-1102"],
        timestamp="2025-03-15T14:30:00Z",
        source_ip="10.0.0.33",
        geo_location="New York, US",
        action_string="open_spreadsheet Q1_Report.xlsx",
        payload_size_mb=12.0,
        device_id="DEV-WIN-1102",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-03-15T08:05:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: Opening a spreadsheet during business hours from known device.",
    ),
    SecurityEvent(
        user_id="USR-4003",
        job_role="HR Manager",
        department="HR",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-1103", "DEV-MOB-1104"],
        timestamp="2025-03-15T16:45:00Z",
        source_ip="10.0.0.44",
        geo_location="Austin, US",
        action_string="email_send external recipient hr_policy.pdf",
        payload_size_mb=3.5,
        device_id="DEV-WIN-1103",
        failed_login_count=0,
        previous_login_location="Austin, US",
        previous_login_timestamp="2025-03-15T09:10:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: HR manager sending policy documents via email during business hours.",
    ),
]


# =============================================================================
# MEDIUM TASK — 15 events, context-dependent, benign traps mixed in
# =============================================================================

MEDIUM_EVENTS: List[SecurityEvent] = [
    # --- TIER 1: CRITICAL (BAN) ---
    SecurityEvent(
        user_id="USR-3101",
        job_role="Contractor",
        department="External",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-3301"],
        timestamp="2025-04-01T08:30:11Z",
        source_ip="185.220.101.45",
        geo_location="Bucharest, Romania",
        action_string="cmd.exe /c vssadmin delete shadows /for=C: /quiet",
        payload_size_mb=0.01,
        device_id="DEV-WIN-3301",
        failed_login_count=0,
        previous_login_location="Bucharest, Romania",
        previous_login_timestamp="2025-04-01T08:00:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Ransomware: vssadmin delete shadows wrapped in cmd.exe execution.",
    ),
    SecurityEvent(
        user_id="USR-3102",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-LIN-3302"],
        timestamp="2025-04-01T11:15:33Z",
        source_ip="10.0.5.88",
        geo_location="San Francisco, US",
        action_string="rundll32.exe comsvcs.dll MiniDump PID lsass.dmp full",
        payload_size_mb=0.2,
        device_id="DEV-LIN-3302",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-01T09:05:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Credential harvesting: LSASS memory dump via comsvcs.dll MiniDump technique.",
    ),

    # --- TIER 2: HIGH (SUSPEND) ---
    SecurityEvent(
        user_id="USR-3201",
        job_role="Product Manager",
        department="Product",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-3401", "DEV-MOB-3402"],
        timestamp="2025-04-01T14:00:00Z",
        source_ip="103.235.46.39",
        geo_location="Mumbai, India",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-MAC-3401",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-04-01T13:30:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Impossible travel: New York to Mumbai in 30 minutes is physically impossible.",
    ),
    SecurityEvent(
        user_id="USR-3202",
        job_role="Support Agent",
        department="Customer Support",
        typical_login_hours="08:00-16:00",
        registered_devices=["DEV-WIN-3501"],
        timestamp="2025-04-01T08:15:00Z",
        source_ip="10.0.3.22",
        geo_location="Denver, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-3501",
        failed_login_count=103,
        previous_login_location="Denver, US",
        previous_login_timestamp="2025-03-31T16:00:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Brute force: 103 consecutive failed logins before a success indicates credential stuffing.",
    ),

    # --- TIER 3: MEDIUM (VERIFY) ---
    SecurityEvent(
        user_id="USR-3301",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-3601"],
        timestamp="2025-04-01T10:00:00Z",
        source_ip="10.0.1.55",
        geo_location="San Francisco, US",
        action_string="file_download repo_backup.tar.gz",
        payload_size_mb=4200.0,
        device_id="DEV-NEW-UNKNOWN",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-01T09:00:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="Insider threat indicator: Unregistered device + 4.2GB download of repository backup.",
    ),
    SecurityEvent(
        user_id="USR-3302",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-3701"],
        timestamp="2025-04-02T01:45:00Z",
        source_ip="10.0.2.66",
        geo_location="New York, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-3701",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-04-01T17:00:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="After-hours login: 1:45 AM login for a 9-5 Financial Analyst is unusual.",
    ),

    # --- BENIGN (PERMIT) - including traps ---

    # TRAP: IT Admin running vssadmin legitimately (NOT ransomware)
    SecurityEvent(
        user_id="USR-3401",
        job_role="IT Administrator",
        department="IT",
        typical_login_hours="07:00-19:00",
        registered_devices=["DEV-WIN-3801", "DEV-SRV-3802"],
        timestamp="2025-04-01T09:30:00Z",
        source_ip="10.0.0.10",
        geo_location="San Francisco, US",
        action_string="vssadmin list shadows",
        payload_size_mb=0.0,
        device_id="DEV-SRV-3802",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-01T07:15:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Legitimate IT operation: 'vssadmin list shadows' (not delete) is a routine backup check by an IT Admin.",
    ),

    # TRAP: Employee forgot password (5 failed logins, NOT brute force)
    SecurityEvent(
        user_id="USR-3402",
        job_role="Designer",
        department="Marketing",
        typical_login_hours="10:00-19:00",
        registered_devices=["DEV-MAC-3803"],
        timestamp="2025-04-01T10:08:00Z",
        source_ip="10.0.2.77",
        geo_location="San Francisco, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-MAC-3803",
        failed_login_count=5,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-03-31T18:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Forgotten password: Only 5 failed attempts from a known device in their usual location. This is a typical forgotten-password pattern, not brute force.",
    ),

    # TRAP: Remote worker logging in from vacation (NOT impossible travel)
    SecurityEvent(
        user_id="USR-3403",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-3804", "DEV-MOB-3805"],
        timestamp="2025-04-01T16:00:00Z",
        source_ip="88.198.50.103",
        geo_location="Berlin, Germany",
        action_string="git pull origin dev",
        payload_size_mb=15.0,
        device_id="DEV-MAC-3804",
        failed_login_count=0,
        previous_login_location="Berlin, Germany",
        previous_login_timestamp="2025-04-01T09:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Remote/vacation worker: Consecutive logins both from Berlin, same registered device. This is not impossible travel.",
    ),

    # Normal activities
    SecurityEvent(
        user_id="USR-3404",
        job_role="Sales Manager",
        department="Sales",
        typical_login_hours="08:00-17:00",
        registered_devices=["DEV-WIN-3806"],
        timestamp="2025-04-01T11:00:00Z",
        source_ip="10.0.0.99",
        geo_location="Chicago, US",
        action_string="crm_update client_record lead_status",
        payload_size_mb=0.1,
        device_id="DEV-WIN-3806",
        failed_login_count=0,
        previous_login_location="Chicago, US",
        previous_login_timestamp="2025-04-01T08:05:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: Routine CRM update during business hours.",
    ),
    SecurityEvent(
        user_id="USR-3405",
        job_role="HR Manager",
        department="HR",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-3807", "DEV-MOB-3808"],
        timestamp="2025-04-01T14:22:00Z",
        source_ip="10.0.0.44",
        geo_location="Austin, US",
        action_string="file_upload performance_review_Q1.docx",
        payload_size_mb=2.3,
        device_id="DEV-WIN-3807",
        failed_login_count=0,
        previous_login_location="Austin, US",
        previous_login_timestamp="2025-04-01T09:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: HR manager uploading performance review during business hours.",
    ),
    SecurityEvent(
        user_id="USR-3406",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-LIN-3809"],
        timestamp="2025-04-01T17:50:00Z",
        source_ip="10.0.1.12",
        geo_location="San Francisco, US",
        action_string="docker build -t app:latest .",
        payload_size_mb=800.0,
        device_id="DEV-LIN-3809",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-01T09:15:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: Docker build during business hours. Large payload is expected for container images.",
    ),

    # TRAP: New employee onboarding (NOT insider threat)
    SecurityEvent(
        user_id="USR-3407",
        job_role="New Hire",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-NEW-001"],
        timestamp="2025-04-01T10:30:00Z",
        source_ip="10.0.1.88",
        geo_location="San Francisco, US",
        action_string="file_download onboarding_materials.zip",
        payload_size_mb=1500.0,
        device_id="DEV-MAC-NEW-001",
        failed_login_count=3,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-01T10:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="New employee onboarding: Device is listed as registered (DEV-MAC-NEW-001). 1.5GB onboarding download and a few failed logins on first day are expected.",
    ),

    # TIER 3: After-hours + VPN login combo
    SecurityEvent(
        user_id="USR-3408",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-3810"],
        timestamp="2025-04-02T04:10:00Z",
        source_ip="104.238.170.55",
        geo_location="VPN - US East",
        action_string="ssh prod-server-01 sudo cat /etc/shadow",
        payload_size_mb=0.01,
        device_id="DEV-MAC-3810",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-01T17:30:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="After-hours access: 4:10 AM SSH to production server reading /etc/shadow via VPN. Unusual time + sensitive file access warrants identity verification.",
    ),

    # BENIGN: Routine mobile check-in
    SecurityEvent(
        user_id="USR-3404",
        job_role="Sales Manager",
        department="Sales",
        typical_login_hours="08:00-17:00",
        registered_devices=["DEV-WIN-3806", "DEV-MOB-3806B"],
        timestamp="2025-04-01T12:30:00Z",
        source_ip="172.16.0.5",
        geo_location="Chicago, US",
        action_string="mobile_app crm_view pipeline_dashboard",
        payload_size_mb=0.5,
        device_id="DEV-MOB-3806B",
        failed_login_count=0,
        previous_login_location="Chicago, US",
        previous_login_timestamp="2025-04-01T11:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal activity: Sales manager checking CRM on registered mobile device during lunch break.",
    ),
]


# =============================================================================
# HARD TASK — 25 events, alert fatigue + adaptive attacker + traps
#
# Structure:
#   Events 1-15: Mostly benign (alert fatigue zone)
#   Events 16-25: Threats become sneakier, attacker adapts
# =============================================================================

HARD_EVENTS: List[SecurityEvent] = [
    # ========= ALERT FATIGUE ZONE (Events 1-15): Mostly benign =========

    # Events 1-8: Pure benign - lull the agent
    SecurityEvent(
        user_id="USR-H001",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-H001"],
        timestamp="2025-05-01T09:05:00Z",
        source_ip="10.0.1.10",
        geo_location="San Francisco, US",
        action_string="git clone repo/frontend.git",
        payload_size_mb=120.0,
        device_id="DEV-MAC-H001",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-30T17:30:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Engineer cloning repo at start of day.",
    ),
    SecurityEvent(
        user_id="USR-H002",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="08:00-17:00",
        registered_devices=["DEV-WIN-H002"],
        timestamp="2025-05-01T08:30:00Z",
        source_ip="10.0.0.22",
        geo_location="New York, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-H002",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-04-30T16:55:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Morning login from usual location.",
    ),
    SecurityEvent(
        user_id="USR-H003",
        job_role="Sales Manager",
        department="Sales",
        typical_login_hours="08:00-18:00",
        registered_devices=["DEV-WIN-H003", "DEV-MOB-H003B"],
        timestamp="2025-05-01T09:15:00Z",
        source_ip="10.0.0.33",
        geo_location="Chicago, US",
        action_string="crm_query pipeline_report Q2",
        payload_size_mb=5.0,
        device_id="DEV-WIN-H003",
        failed_login_count=0,
        previous_login_location="Chicago, US",
        previous_login_timestamp="2025-04-30T17:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Sales pipeline query during business hours.",
    ),
    SecurityEvent(
        user_id="USR-H004",
        job_role="Designer",
        department="Marketing",
        typical_login_hours="10:00-19:00",
        registered_devices=["DEV-MAC-H004"],
        timestamp="2025-05-01T10:20:00Z",
        source_ip="10.0.2.44",
        geo_location="San Francisco, US",
        action_string="figma_export campaign_assets.zip",
        payload_size_mb=350.0,
        device_id="DEV-MAC-H004",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-04-30T18:30:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Designer exporting Figma assets during work hours.",
    ),
    SecurityEvent(
        user_id="USR-H005",
        job_role="HR Manager",
        department="HR",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-H005"],
        timestamp="2025-05-01T11:00:00Z",
        source_ip="10.0.0.55",
        geo_location="Austin, US",
        action_string="file_upload employee_handbook_v3.pdf",
        payload_size_mb=8.5,
        device_id="DEV-WIN-H005",
        failed_login_count=0,
        previous_login_location="Austin, US",
        previous_login_timestamp="2025-05-01T09:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: HR document upload during business hours.",
    ),
    SecurityEvent(
        user_id="USR-H006",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-LIN-H006"],
        timestamp="2025-05-01T11:30:00Z",
        source_ip="10.0.1.66",
        geo_location="San Francisco, US",
        action_string="kubectl apply -f deployment.yaml",
        payload_size_mb=0.01,
        device_id="DEV-LIN-H006",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-01T09:10:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Kubernetes deployment during business hours.",
    ),
    SecurityEvent(
        user_id="USR-H007",
        job_role="Support Agent",
        department="Customer Support",
        typical_login_hours="08:00-16:00",
        registered_devices=["DEV-WIN-H007"],
        timestamp="2025-05-01T12:00:00Z",
        source_ip="10.0.3.77",
        geo_location="Denver, US",
        action_string="ticket_resolve TICKET-44821 resolved",
        payload_size_mb=0.01,
        device_id="DEV-WIN-H007",
        failed_login_count=0,
        previous_login_location="Denver, US",
        previous_login_timestamp="2025-05-01T08:05:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Support agent resolving ticket during shift.",
    ),
    SecurityEvent(
        user_id="USR-H001",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-H001"],
        timestamp="2025-05-01T13:00:00Z",
        source_ip="10.0.1.10",
        geo_location="San Francisco, US",
        action_string="npm run test",
        payload_size_mb=0.5,
        device_id="DEV-MAC-H001",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-01T09:05:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Running test suite during business hours.",
    ),

    # Event 9: First REAL threat in the fatigue zone (TIER 3 - VERIFY)
    SecurityEvent(
        user_id="USR-H008",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-H008"],
        timestamp="2025-05-01T23:45:00Z",
        source_ip="10.0.0.88",
        geo_location="New York, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-H008",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-05-01T16:50:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="After-hours login: 11:45 PM login for a 9-5 Finance Analyst.",
    ),

    # Events 10-14: More benign to rebuild fatigue
    SecurityEvent(
        user_id="USR-H002",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="08:00-17:00",
        registered_devices=["DEV-WIN-H002"],
        timestamp="2025-05-02T08:15:00Z",
        source_ip="10.0.0.22",
        geo_location="New York, US",
        action_string="open_spreadsheet monthly_expenses.xlsx",
        payload_size_mb=25.0,
        device_id="DEV-WIN-H002",
        failed_login_count=0,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-05-01T16:55:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Morning spreadsheet work.",
    ),
    SecurityEvent(
        user_id="USR-H003",
        job_role="Sales Manager",
        department="Sales",
        typical_login_hours="08:00-18:00",
        registered_devices=["DEV-WIN-H003", "DEV-MOB-H003B"],
        timestamp="2025-05-02T09:00:00Z",
        source_ip="10.0.0.33",
        geo_location="Chicago, US",
        action_string="email_send external client_proposal.pdf",
        payload_size_mb=4.5,
        device_id="DEV-WIN-H003",
        failed_login_count=0,
        previous_login_location="Chicago, US",
        previous_login_timestamp="2025-05-02T08:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Sales sending client proposal.",
    ),
    SecurityEvent(
        user_id="USR-H006",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-LIN-H006"],
        timestamp="2025-05-02T10:30:00Z",
        source_ip="10.0.1.66",
        geo_location="San Francisco, US",
        action_string="docker push registry.internal/app:v2.3.1",
        payload_size_mb=950.0,
        device_id="DEV-LIN-H006",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T09:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Pushing Docker image to internal registry.",
    ),

    # TRAP: IT Admin doing legitimate LSASS diagnostic (NOT credential theft)
    SecurityEvent(
        user_id="USR-H009",
        job_role="IT Administrator",
        department="IT",
        typical_login_hours="07:00-19:00",
        registered_devices=["DEV-WIN-H009", "DEV-SRV-H009B"],
        timestamp="2025-05-02T11:00:00Z",
        source_ip="10.0.0.5",
        geo_location="San Francisco, US",
        action_string="tasklist /fi \"imagename eq lsass.exe\" /v",
        payload_size_mb=0.0,
        device_id="DEV-SRV-H009B",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T07:30:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Legitimate IT operation: 'tasklist' to VIEW lsass process info (not dump) is routine diagnostics by IT Admin.",
    ),
    SecurityEvent(
        user_id="USR-H004",
        job_role="Designer",
        department="Marketing",
        typical_login_hours="10:00-19:00",
        registered_devices=["DEV-MAC-H004"],
        timestamp="2025-05-02T14:00:00Z",
        source_ip="10.0.2.44",
        geo_location="San Francisco, US",
        action_string="slack_message #design channel review_request",
        payload_size_mb=0.01,
        device_id="DEV-MAC-H004",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T10:15:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Normal: Slack message during work hours.",
    ),

    # ========= THREAT ZONE (Events 15-25): Attacker adapts =========

    # Event 15: TIER 2 - Impossible travel (standard signature)
    SecurityEvent(
        user_id="USR-H010",
        job_role="Product Manager",
        department="Product",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-H010", "DEV-MOB-H010B"],
        timestamp="2025-05-02T15:30:00Z",
        source_ip="41.58.120.88",
        geo_location="Lagos, Nigeria",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-MAC-H010",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T15:00:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Impossible travel: San Francisco to Lagos in 30 minutes is impossible.",
    ),

    # Event 16: TIER 1 - Obvious ransomware
    SecurityEvent(
        user_id="USR-H011",
        job_role="Contractor",
        department="External",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-H011"],
        timestamp="2025-05-02T16:00:00Z",
        source_ip="192.0.2.111",
        geo_location="Unknown Proxy",
        action_string="wmic shadowcopy delete",
        payload_size_mb=0.01,
        device_id="DEV-WIN-H011",
        failed_login_count=0,
        previous_login_location="Unknown Proxy",
        previous_login_timestamp="2025-05-02T15:50:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Ransomware variant: 'wmic shadowcopy delete' is an alternative method to delete shadow copies.",
    ),

    # Event 17: TIER 1 - Adapted credential theft (uses ntdsutil instead of mimikatz)
    SecurityEvent(
        user_id="USR-H012",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-WIN-H012"],
        timestamp="2025-05-02T16:30:00Z",
        source_ip="10.0.5.99",
        geo_location="San Francisco, US",
        action_string='ntdsutil "activate instance ntds" "ifm" "create full c:\\temp\\ntds_dump" quit quit',
        payload_size_mb=0.5,
        device_id="DEV-WIN-H012",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T09:00:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Credential theft: ntdsutil IFM dump extracts entire Active Directory database including password hashes.",
    ),

    # Event 18: TRAP — Benign that looks like brute force
    SecurityEvent(
        user_id="USR-H013",
        job_role="Intern",
        department="Engineering",
        typical_login_hours="10:00-18:00",
        registered_devices=["DEV-WIN-H013"],
        timestamp="2025-05-02T10:12:00Z",
        source_ip="10.0.1.55",
        geo_location="San Francisco, US",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-H013",
        failed_login_count=8,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-01T17:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Forgotten password: 8 failed attempts from known device at usual location. Interns frequently forget credentials on early days.",
    ),

    # Event 19: TIER 3 — Subtle insider threat
    SecurityEvent(
        user_id="USR-H014",
        job_role="Engineer",
        department="Engineering",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-H014"],
        timestamp="2025-05-02T17:55:00Z",
        source_ip="10.0.1.77",
        geo_location="San Francisco, US",
        action_string="file_download customer_database_full_export.sql",
        payload_size_mb=6800.0,
        device_id="DEV-USB-EXTERNAL",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T09:00:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="Insider threat: Unregistered USB device + massive 6.8GB customer database download just before end of business.",
    ),

    # Event 20: TIER 2 - Brute force with adapted count (exactly 100)
    SecurityEvent(
        user_id="USR-H015",
        job_role="Analyst",
        department="Finance",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-H015"],
        timestamp="2025-05-02T18:30:00Z",
        source_ip="203.0.113.44",
        geo_location="Seoul, South Korea",
        action_string="login_success",
        payload_size_mb=0.0,
        device_id="DEV-WIN-H015",
        failed_login_count=100,
        previous_login_location="New York, US",
        previous_login_timestamp="2025-05-02T17:00:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Brute force: 100 failed logins + impossible travel (New York to Seoul in 1.5 hours). Double indicators.",
    ),

    # Event 21: TIER 1 - Adapted ransomware (PowerShell variant)
    SecurityEvent(
        user_id="USR-H016",
        job_role="Contractor",
        department="External",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-H016"],
        timestamp="2025-05-02T19:00:00Z",
        source_ip="185.220.103.7",
        geo_location="Tor Exit Node",
        action_string="powershell.exe -enc UmVtb3ZlLVdtaU9iamVjdCAtQ2xhc3MgV2luMzJfU2hhZG93Q29weQ==",
        payload_size_mb=0.01,
        device_id="DEV-WIN-H016",
        failed_login_count=0,
        previous_login_location="Tor Exit Node",
        previous_login_timestamp="2025-05-02T18:50:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Obfuscated ransomware: Base64-encoded PowerShell that decodes to 'Remove-WmiObject -Class Win32_ShadowCopy' — shadow copy deletion.",
    ),

    # Event 22: TRAP — Legitimate large transfer by DataOps
    SecurityEvent(
        user_id="USR-H017",
        job_role="Data Engineer",
        department="Engineering",
        typical_login_hours="08:00-18:00",
        registered_devices=["DEV-LIN-H017"],
        timestamp="2025-05-02T14:00:00Z",
        source_ip="10.0.5.20",
        geo_location="San Francisco, US",
        action_string="pg_dump --format=custom production_db > backup_20250502.dump",
        payload_size_mb=15000.0,
        device_id="DEV-LIN-H017",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T08:00:00Z",
        correct_action="PERMIT",
        threat_tier="BENIGN",
        explanation="Legitimate operation: Data Engineer performing scheduled database backup from registered device during business hours. Large payload expected.",
    ),

    # Event 23: TIER 3 — After hours + new device combo
    SecurityEvent(
        user_id="USR-H018",
        job_role="Product Manager",
        department="Product",
        typical_login_hours="09:00-18:00",
        registered_devices=["DEV-MAC-H018"],
        timestamp="2025-05-03T02:15:00Z",
        source_ip="73.162.55.100",
        geo_location="San Francisco, US",
        action_string="file_download strategic_roadmap_2026.pptx",
        payload_size_mb=85.0,
        device_id="DEV-WIN-PERSONAL",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-02T17:30:00Z",
        correct_action="VERIFY",
        threat_tier="TIER_3_MEDIUM",
        explanation="Suspicious combo: 2:15 AM access from unregistered personal device downloading strategic documents.",
    ),

    # Event 24: TIER 1 — Adapted credential theft (reg.exe export of SAM)
    SecurityEvent(
        user_id="USR-H019",
        job_role="Contractor",
        department="External",
        typical_login_hours="09:00-17:00",
        registered_devices=["DEV-WIN-H019"],
        timestamp="2025-05-03T03:00:00Z",
        source_ip="192.0.2.200",
        geo_location="Unknown VPN",
        action_string="reg save HKLM\\SAM c:\\temp\\sam.hive",
        payload_size_mb=0.1,
        device_id="DEV-WIN-H019",
        failed_login_count=0,
        previous_login_location="Unknown VPN",
        previous_login_timestamp="2025-05-03T02:50:00Z",
        correct_action="BAN",
        threat_tier="TIER_1_CRITICAL",
        explanation="Credential theft: Exporting SAM registry hive allows offline password hash cracking.",
    ),

    # Event 25: TIER 2 — Impossible travel with device spoofing
    SecurityEvent(
        user_id="USR-H020",
        job_role="VP of Engineering",
        department="Engineering",
        typical_login_hours="08:00-20:00",
        registered_devices=["DEV-MAC-H020", "DEV-MOB-H020B"],
        timestamp="2025-05-03T04:00:00Z",
        source_ip="5.255.255.77",
        geo_location="Moscow, Russia",
        action_string="login_success admin_console",
        payload_size_mb=0.0,
        device_id="DEV-MAC-H020",
        failed_login_count=0,
        previous_login_location="San Francisco, US",
        previous_login_timestamp="2025-05-03T03:30:00Z",
        correct_action="SUSPEND",
        threat_tier="TIER_2_HIGH",
        explanation="Impossible travel with escalation: SF to Moscow in 30 minutes, accessing admin console. Device ID may be spoofed.",
    ),
]


# Mapping task names to event lists
TASK_EVENTS = {
    "soc_easy": EASY_EVENTS,
    "soc_medium": MEDIUM_EVENTS,
    "soc_hard": HARD_EVENTS,
}

TASK_LIST = list(TASK_EVENTS.keys())
